### ISSUE TITLE
onSlidingComplete?

### ISSUE THREAD

**Issue by felixaa** [Enrise/react-native-nmrangeslider-ios#6]
Is there a onSlidingComplete property available? Instead of the expensive onChange?

**Comment by felixaa** [comment]
I noticed in the example gif. The age-text updates when you release the slider. Any sample code on this?
Am I missing the event-callback for onChangeComplete?

**Comment by adri** [comment]
@felixaa Hi, what we did was to [debounce](https://lodash.com/docs#debounce) the `onChange` by a few ms before calling `setState`. Is that what you are looking for?

**Comment by felixaa** [comment]
That works! Thanks for help and quick response! 👍
